# Generated by Django 3.1.4 on 2020-12-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblog',
            name='datecompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userblog',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
