# Generated by Django 3.1.4 on 2020-12-17 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('profession', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=200)),
                ('skills', models.TextField(max_length=200)),
                ('photo', models.ImageField(upload_to='aboutme/images/')),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
