# Generated by Django 3.1.4 on 2020-12-17 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='about',
            name='skills',
            field=models.TextField(max_length=500),
        ),
    ]
