# Generated by Django 3.1.4 on 2020-12-19 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aboutme', '0002_auto_20201217_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='photo',
            new_name='image',
        ),
    ]
